require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TouristDestinationsController do

  # This should return the minimal set of attributes required to create a valid
  # TouristDestination. As you add validations to TouristDestination, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString", "description" =>
                             "MyDescription" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TouristDestinationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tourist_destinations as @tourist_destinations" do
      tourist_destination = TouristDestination.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:tourist_destinations)).to eq([tourist_destination])
    end
  end

  describe "GET show" do
    it "assigns the requested tourist_destination as @tourist_destination" do
      tourist_destination = TouristDestination.create! valid_attributes
      get :show, {:id => tourist_destination.to_param}, valid_session
      expect(assigns(:tourist_destination)).to eq(tourist_destination)
    end
  end

  describe "GET new" do
    it "assigns a new tourist_destination as @tourist_destination" do
      get :new, {}, valid_session
      expect(assigns(:tourist_destination)).to be_a_new(TouristDestination)
    end
  end

  describe "GET edit" do
    it "assigns the requested tourist_destination as @tourist_destination" do
      tourist_destination = TouristDestination.create! valid_attributes
      get :edit, {:id => tourist_destination.to_param}, valid_session
      expect(assigns(:tourist_destination)).to eq(tourist_destination)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TouristDestination" do
        expect {
          post :create, {:tourist_destination => valid_attributes}, valid_session
        }.to change(TouristDestination, :count).by(1)
      end

      it "assigns a newly created tourist_destination as @tourist_destination" do
        post :create, {:tourist_destination => valid_attributes}, valid_session
        expect(assigns(:tourist_destination)).to be_a(TouristDestination)
        expect(assigns(:tourist_destination)).to be_persisted
      end

      it "redirects to the created tourist_destination" do
        post :create, {:tourist_destination => valid_attributes}, valid_session
        expect(response).to redirect_to(TouristDestination.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tourist_destination as @tourist_destination" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TouristDestination).to receive(:save).and_return(false)
        post :create, {:tourist_destination => { "title" => "invalid value" }}, valid_session
        expect(assigns(:tourist_destination)).to be_a_new(TouristDestination)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TouristDestination).to receive(:save).and_return(false)
        post :create, {:tourist_destination => { "title" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tourist_destination" do
        tourist_destination = TouristDestination.create! valid_attributes
        # Assuming there are no other tourist_destinations in the database, this
        # specifies that the TouristDestination created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(TouristDestination).to receive(:update).with({ "title" => "MyString" })
        put :update, {:id => tourist_destination.to_param, :tourist_destination => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested tourist_destination as @tourist_destination" do
        tourist_destination = TouristDestination.create! valid_attributes
        put :update, {:id => tourist_destination.to_param, :tourist_destination => valid_attributes}, valid_session
        expect(assigns(:tourist_destination)).to eq(tourist_destination)
      end

      it "redirects to the tourist_destination" do
        tourist_destination = TouristDestination.create! valid_attributes
        put :update, {:id => tourist_destination.to_param, :tourist_destination => valid_attributes}, valid_session
        expect(response).to redirect_to(tourist_destination)
      end
    end

    describe "with invalid params" do
      it "assigns the tourist_destination as @tourist_destination" do
        tourist_destination = TouristDestination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TouristDestination).to receive(:save).and_return(false)
        put :update, {:id => tourist_destination.to_param, :tourist_destination => { "title" => "invalid value" }}, valid_session
        expect(assigns(:tourist_destination)).to eq(tourist_destination)
      end

      it "re-renders the 'edit' template" do
        tourist_destination = TouristDestination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(TouristDestination).to receive(:save).and_return(false)
        put :update, {:id => tourist_destination.to_param, :tourist_destination => { "title" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tourist_destination" do
      tourist_destination = TouristDestination.create! valid_attributes
      expect {
        delete :destroy, {:id => tourist_destination.to_param}, valid_session
      }.to change(TouristDestination, :count).by(-1)
    end

    it "redirects to the tourist_destinations list" do
      tourist_destination = TouristDestination.create! valid_attributes
      delete :destroy, {:id => tourist_destination.to_param}, valid_session
      expect(response).to redirect_to(tourist_destinations_url)
    end
  end

end
