require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TouristDestinationsController do

  let(:tourist_destination) { mock_model TouristDestination }
  let(:tourist_destination_id) { '42' }

  describe "GET index" do
    it "assigns all tourist_destinations as @tourist_destinations" do
      expect(TouristDestination).to receive(:all).and_return('tourist_destination')

      get :index

      expect(assigns(:tourist_destinations)).to eq('tourist_destination')
    end
  end

  describe "GET show" do
    it "looks up the tourist_destination by id" do
      expect(TouristDestination).to receive(:find).with(tourist_destination_id)

      get :show, id: tourist_destination_id
    end

    it "assigns the requested tourist_destination as @tourist_destination" do
      expect(TouristDestination).to receive(:find).and_return(tourist_destination)

      get :show, id: tourist_destination_id

      expect(assigns(:tourist_destination)).to eq(tourist_destination)
    end
  end

  describe "GET new" do
    it "assigns a new tourist_destination as @tourist_destination" do
      expect(TouristDestination).to receive(:new).and_return(tourist_destination)

      get :new

      expect(assigns(:tourist_destination)).to eq(tourist_destination)
    end
  end

  describe "GET edit" do
    it "assigns the requested tourist_destination as @tourist_destination" do
      expect(TouristDestination).to receive(:find).with(tourist_destination_id).
        and_return('tourist_destination')

      get :edit, id: tourist_destination_id

      expect(assigns(:tourist_destination)).to eq('tourist_destination')
    end
  end

  describe "POST create" do
    let(:arguments) { 'tourist_destination_arguments' }

    def create_toutirst_destination
      post :create, tourist_destination: arguments
    end

    before do
      allow(TouristDestination).to receive(:new).and_return(tourist_destination)
      allow(tourist_destination).to receive(:save)
      expect(arguments).to receive(:permit).and_return(arguments)
    end

    describe "with valid params" do
      it "initiatializes a new TouristDestination with params[:tourist_destination]" do
        expect(TouristDestination).to receive(:new).with('tourist_destination_arguments').
          and_return(tourist_destination)

        create_toutirst_destination
      end

      it "assigns a newly created tourist_destination as @tourist_destination" do
        create_toutirst_destination

        expect(assigns(:tourist_destination)).to eq(tourist_destination)
      end

      it "redirects to the created tourist_destination" do
        expect(tourist_destination).to receive(:save).and_return(true)

        create_toutirst_destination

        expect(response).to redirect_to(tourist_destination)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tourist_destination as @tourist_destination" do
        expect(tourist_destination).to receive(:save).and_return(false)

        create_toutirst_destination

        expect(assigns(:tourist_destination)).to eq(tourist_destination)
      end

      it "re-renders the 'new' template" do
        expect(tourist_destination).to receive(:save).and_return(false)

        create_toutirst_destination

        expect(response).to render_template :new
      end
    end
  end

  describe "PUT update" do
    let(:arguments) { 'tourist_destination_arguments' }

    def update_tourist_destination
      put :update, id: tourist_destination_id, tourist_destination: arguments
    end

    before do
      allow(TouristDestination).to receive(:find).and_return(tourist_destination)
      expect(arguments).to receive(:permit).and_return(arguments)
      allow(tourist_destination).to receive(:update).and_return(false)
    end

    describe "with valid params" do
      it "looks up the TouristDestination by id" do
        expect(TouristDestination).to receive(:find).with(tourist_destination_id).
          and_return(tourist_destination)

        update_tourist_destination
      end

      it "invokes update with params[:tourist_destination]" do
        expect(tourist_destination).to receive(:update).with(arguments)

        update_tourist_destination
      end

      it "assigns the requested tourist_destination as @tourist_destination" do
        update_tourist_destination

        expect(assigns(:tourist_destination)).to eq(tourist_destination)
      end

      it "redirects to the tourist_destination on success" do
        expect(tourist_destination).to receive(:update).with(arguments).
          and_return(true)

        update_tourist_destination

        expect(response).to redirect_to(tourist_destination)
      end
    end

    describe "with invalid params" do
      it "assigns the tourist_destination as @tourist_destination" do
        update_tourist_destination

        expect(assigns(:tourist_destination)).to eq(tourist_destination)
      end

      it "re-renders the 'edit' template" do
        update_tourist_destination

        expect(response).to render_template(:edit)
      end
    end
  end

  describe "DELETE destroy" do
    before do
      allow(TouristDestination).to receive(:find).and_return(tourist_destination)
      allow(tourist_destination).to receive(:destroy)
    end

    def delete_tourist_destination
      delete :destroy, id: tourist_destination_id
    end

    it "looks up the tourist_destination by id" do
      expect(TouristDestination).to receive(:find).and_return(tourist_destination)

      delete_tourist_destination
    end

    it "attempts to destroy the requested tourist_destination" do
      expect(tourist_destination).to receive(:destroy)

      delete_tourist_destination
    end

    it "redirects to the tourist_destinations list" do
      delete_tourist_destination

      expect(response).to redirect_to(tourist_destinations_url)
    end
  end

end
